const api_data = {
    "login": "ParthPanchal26",
    "id": 120961309,
    "node_id": "U_kgDOBzW5HQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/120961309?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ParthPanchal26",
    "html_url": "https://github.com/ParthPanchal26",
    "followers_url": "https://api.github.com/users/ParthPanchal26/followers",
    "following_url": "https://api.github.com/users/ParthPanchal26/following{/other_user}",
    "gists_url": "https://api.github.com/users/ParthPanchal26/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ParthPanchal26/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ParthPanchal26/subscriptions",
    "organizations_url": "https://api.github.com/users/ParthPanchal26/orgs",
    "repos_url": "https://api.github.com/users/ParthPanchal26/repos",
    "events_url": "https://api.github.com/users/ParthPanchal26/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ParthPanchal26/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Parth Panchal",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 3,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2022-12-18T16:31:45Z",
    "updated_at": "2024-02-06T03:17:44Z"
}

module.exports =  api_data;